#!/usr/bin/env ruby
require "rubygems" # for Ruby 1.8
require "thor"

class DotFiles < Thor
  include Thor::Actions

  desc "link", "Make symbolic links for all dotfiles"
  def link
    dotfiles.each do |name|
      do_link(name)
    end
  end

  # desc "copy", "Make copy for all dotfiles"
  # def copy
  #   dotfiles.each do |name|
  #     do_copy(name)
  #   end
  # end

  desc "list", "List dotfiles that need to process"
  def list
    dotfiles.each do |name|
      say name
    end
  end

  no_tasks do
    def dotfiles
      # Dir['*'].each do |file|
      %w{bashrc bash_profile bash irbrc}
    end

    def do_link(name)
      # TODO: beware to nuke your dotfile lol
      run "ln -sfn #{src_dir}/#{name} ~/.#{name}"
    end

    # def do_copy(name)
    #   source = "#{src_dir}/#{name}"
    #   target = "#{ENV['HOME']}/#{name}"
    #   if File.symlink?(target)
    #     say_status :unlink, target
    #     File.unlink(target)
    #   end
    #   run "cp #{src_dir}/#{name} ~/#{name}"
    # end

    def src_dir
      @src_dir ||= File.expand_path(File.dirname(__FILE__))
    end
  end
end

DotFiles.start

