#!/usr/bin/env ruby
require "rubygems" # for Ruby 1.8
require "thor"

class DotFiles < Thor
  include Thor::Actions

  desc "install", "Make symbolic links for all dotfiles"
  def install
    dotfiles.each do |name|
      process(name)
    end
  end

  desc "list", "List dotfiles that need to process"
  def list
    dotfiles.each do |name|
      say(name)
    end
  end

  no_tasks do
    def dotfiles
      # Dir['*'].each do |file|

      # Whitelist is always more safe :)
      %w{bashrc bash_profile bash irbrc rails-templates gemrc screenrc bin richrc}
    end

    def process(name)
      @filename = name
      if File.exists?(target)
        if File.identical?(source, target)
          say_status :identical, @filename
        else
          link! if yes?("Overwrite #{target}?")
        end
      else
        link!
      end
      @filename = nil
    end

    def link!
      run "ln -sfn #{source} #{target}"
    end

    def source
      "#{src_dir}/#{@filename}"
    end

    def target
      "#{ENV['HOME']}/.#{@filename}"
    end

    def src_dir
      File.expand_path(File.dirname(__FILE__))
    end

  end
end

DotFiles.start
